### ISSUE TITLE
.Net RFC-6455

### ISSUE THREAD

**Issue by sbadugu** [Sadfras/Testing-Matrix#6]
**Sprint Goals**
Goal for this sprint is to finish [.Net RFC-6455] (https://github.com/kaazing/roadmap/issues/2) related tasks.

**Sprint Task List**
Following are the list of tasks for this sprint:
- [ ] [Functional Spec Doc](https://github.com/Sadfras/Testing-Matrix/issues/2) (2 days) 
- [ ] Investigate a way to build PCL(Portable Class Library) dll (2 weeks)
- [ ] [Change maven build from Npandy to Msbuild](https://github.com/Sadfras/Testing-Matrix/issues/1) (1 day)
- [ ] [Change itests to be able to run on all platforms (Windows 8 Desktop, Windows 8 Phone and Windows 7 + silverlight for all platforms](https://github.com/Sadfras/Testing-Matrix/issues/4) (1 week)

**Sprint Blocker**
None.

**Sprint Deliverables**
Following deliverables will benefit customers:
- [ ] Ability to run native web-socket on .NET client.

**Comment by sbadugu** [comment]
This issue was moved to kaazing-private/sandbox.jira.migration#28
